"""video source_url

Revision ID: 43f61b79d074
Revises: 6e937e8c8009
Create Date: 2026-09-25 11:46:14.179636

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43f61b79d074'
down_revision: str | Sequence[str] | None = '6e937e8c8009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=2048), nullable=True))
        batch_op.alter_column('source_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # URL videos that were never downloaded have no file; NOT NULL needs a value.
    op.execute("UPDATE videos SET source_path = '' WHERE source_path IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('source_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
