#!/usr/bin/env sh
# Regenerate requirements.lock (runtime) and requirements-dev.lock (dev extras only) from the loose
# requirements*.txt, inside the same base image the Dockerfile uses, so the pins match production.
#   sh scripts/lock_requirements.sh        (needs Docker; run from the repo root)
set -eu
SRC="$(pwd -W 2>/dev/null || pwd)"   # Git Bash on Windows: a path docker.exe understands
MSYS_NO_PATHCONV=1 docker run --rm -v "$SRC:/src" -w /src python:3.12-slim sh -ec '
  export PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_ROOT_USER_ACTION=ignore
  pip install -q --index-url https://download.pytorch.org/whl/cpu torch
  pip install -q -r requirements.txt
  { echo "# Generated by scripts/lock_requirements.sh from requirements.txt - do not edit by hand."
    pip freeze; } > requirements.lock
  pip install -q -c requirements.lock -r requirements-dev.txt
  { echo "# Generated by scripts/lock_requirements.sh - dev-only packages; install with requirements.lock."
    pip freeze | grep -vxFf requirements.lock; } > requirements-dev.lock
'
echo "wrote requirements.lock and requirements-dev.lock"
